main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about'), 
    path('profile/', views.profile_index, name='index'),
    path('jobs/', views.JobList.as_view(), name='job_index'), 
    path('projects/', views.ProjectList.as_view(), name='projects_index'), 
    path('jobs/<int:pk>/', views.JobDetail.as_view(), name='job_detail'), 
    path('jobs/create/', views.JobCreate.as_view(), name='job_create'), 
    path('projects/create', views.ProjectCreate.as_view(), name='project_create'), 
    path('projects/<int:pk>/', views.ProjectDetail.as_view(), name='project_detail'),
    path('projects/<int:project_id>/add_comment/', views.add_comment, name='add_comment'),     
    path('jobs/<int:pk>/update/', views.JobUpdate.as_view(), name='job_update'),
    path('jobs/<int:pk>/delete/', views.JobDelete.as_view(), name='job_delete'), 
    path('projects/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'), 
    path('projects/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('memes/add_photo/', views.add_photo, name='add_photo'),
    path('memes/', views.PhotoList.as_view(), name='photo_list'),
    path('profile/<int:profile_id>/add_profile_photo/', views.add_profile_photo, name='add_profile_photo'),
]

stayconnected/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.urls import reverse
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    link = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'pk': self.id})

class Job(models.Model):
    company_name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    link = models.CharField(max_length=200)
    salary_min = models.IntegerField()
    salary_max = models.IntegerField()
    date = models.DateField('Date Posted')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('job_detail', kwargs={'pk': self.id})

class Profile(models.Model):
    username = models.CharField(max_length=50)
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
        primary_key=True,
        )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    print(sender, instance, created)
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

def get_absolute_url(self):
    return reverse('detail', kwargs={'profile_id': self.pk})
        


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['created_on']

class Photo(models.Model):
    url = models.CharField(max_length=200)


    def __str__(self):
        return f"Photo for: @{self.url}"

class ProfilePhoto(models.Model):
    url = models.CharField(max_length=200, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Photo for profile_id: {self.profile_id} {self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Job, Project, Profile, Comment


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['company_name', 'title', 'link',
                  'salary_min', 'salary_max', 'date']


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'link']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['username', 'user']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', 'author']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Project, Job, Profile, Photo, ProfilePhoto
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
import uuid
import boto3
from .forms import CommentForm
import botocore
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'sei-stay-connected'
my_key = os.environ['AWS_SECRET_ACCESS_KEY']

def home(request):
    return HttpResponseRedirect('/about/')


def about(request):
    return render(request, 'about.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(user, 'this is the user')
            print(dir(user))
            login(request, user)
            return redirect('index')

        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


@login_required
def profile_index(request):
    profile = Profile.objects.get(user=request.user)
    projects = Project.objects.filter(user=request.user)
    profile_pic = profile.profilephoto_set.last()
    print(profile_pic)
    return render(request, 'profile/detail.html', {'profile': profile, 'projects': projects, 'profile_pic':profile_pic})



def add_comment(request, project_id):

    form = CommentForm(request.POST)

    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.project_id = project_id
        new_comment.save()
    return redirect('project_detail', project_id)


class ProjectList(LoginRequiredMixin, ListView):
    model = Project
    template = 'job_list.html'


class JobList(ListView):
    model = Job


class JobDetail(DetailView):
    model = Job


class JobCreate(LoginRequiredMixin, CreateView):
    model = Job
    fields = '__all__'


class ProjectDetail(LoginRequiredMixin, DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = '__all__'


class JobUpdate(LoginRequiredMixin, UpdateView):
    model = Job
    fields = '__all__'


class JobDelete(LoginRequiredMixin, DeleteView):
    model = Job
    success_url = '/profile/'


class ProjectUpdate(LoginRequiredMixin, UpdateView):
    model = Project
    fields = '__all__'


class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = '/profile/'


def add_photo(request):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')

        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]

        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url)
            photo.save()
        except botocore.exceptions.ClientError as error:
            print(error, " <-this aws error")
    return redirect('photo_list')


class PhotoList(ListView):
    model = Photo
    template = 'photo_list.html'

def add_profile_photo(request, profile_id):
    photo_file = request.FILES.get('photo-file', None)

    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            ProfilePhoto.objects.create(url=url, profile_id=profile_id)

        except:
            print('An error occurred uploading file to s3, is your access key correct?')
    return redirect('index')

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

    <h1>About SEI Stay Connected</h1>
    <hr />
    <p>Created By Khalil, Charles, Karissa and John!</p>
    <footer>Join us and stay connected &copy; 2022 Team[0]</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SEI Stay Connected</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
    rel="stylesheet">
  {% block extrahead %}

  {% endblock extrahead %}
</head>

<body>
  <header class="header-transparent" id='header'>
    <div class='icon-wrapper'>
      <a href="{% url 'about' %}" class='brand-link'><img class="brand-icon"
          src="{% static 'images/SEISC-Logo-Main.png' %}"></a>
    </div>
    {% if user.is_authenticated %}
    <div class='links-holder' id='job-holder'>
      <div class='underline-animation' id='jobs'>JOBS</div>
      <a href="{% url 'job_create' %}" class='job-link underline-animation' id='job-add'>ADD JOB</a>
      <a href="{% url 'job_index' %}" class='job-link underline-animation' id='job-view'>VIEW JOBS</a>
    </div>
    <div class='links-holder'>
      <a href="{% url 'photo_list' %}" class='underline-animation' id='photo-view'>MEMES</a>
    </div>
    <div class='links-holder'>
      <div id='projects' class='underline-animation'>PROJECTS</div>
      <a href="{% url 'project_create' %}" class='project-link underline-animation' id='project-add'>ADD PROJECT</a>
      <a href="{% url 'projects_index' %}" class='project-link underline-animation' id='project-view'>VIEW PROJECTS</a>
    </div>
    <div class="profile-management">
      <a href="{% url 'index' %}" class="underline-animation">MY PROFILE</a>
      <a href="{% url 'logout' %}" class="underline-animation">LOG-OUT</a>
    </div>
    {% else %}
    <div class='links-holder' id='job-holder'>
      <a href="{% url 'job_index' %}" class='underline-animation' id='job-view-guest'>JOBS</a>
    </div>
    <div class='links-holder'>
      <a href="{% url 'photo_list' %}" class='underline-animation' id='photo-view'>MEMES</a>
    </div>
    <div class="profile-management" id='no-user-profile-management'>
      <a href="{% url 'signup' %}" class='underline-animation'>SIGN UP</a>
      <a href="{% url 'login' %}" class="underline-animation">LOG-IN</a>
    </div>
    {% endif %}
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">Join us and stay connected &copy; 2022 Team[0] &nbsp;</div>
  </footer>
</body>
<script src="{% static 'scripts/header.js' %}"></script>

</html>

main_app/templates/main_app/job_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Job</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.company_name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'job_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/job_detail.html
{% extends 'base.html'%}
{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/detail.css' %}">
{% endblock extrahead %}

{% block content %}
{% load humanize %}

<h1>Job Details</h1>


<div class="card">
    <div class="card-content">
        <div class="card-left">
            <span class="card-title">{{ job.company_name }}</span>
            <span class="card-undertitle">{{ job.title }}</span>
            <br>
            <br>
            <div>Salary range: ${{ job.salary_min|intcomma }} - ${{ job.salary_max|intcomma }}</div>
            <a href={{ job.link }} target="_blank" class="card-link card-animation">Link to Job Posting</a>
        </div>
        <div class="user-date">{{ job.date }} </div>
    </div>
    <div class="card-action" id="card-bottom">
        <a id='edit' class='underline-animation' href="{% url 'job_update' job.id %}">Edit</a>
        <a id='delete' class='underline-animation' href="{% url 'job_delete' job.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/job_form.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/forms.css' %}">
{% endblock extrahead %}
{% block content %}

<form action="" method="post">
  <fieldset id='form-fieldset'>
    <legend>
      {% if object %}
      Edit {{object.company_name}}
      {% else %}
      New Job
      {% endif %}
    </legend>

    {% csrf_token %}
    <table>

      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </fieldset>
</form>

<script>

  const dateEl = document.querySelector('#id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  })

  const selectEl = document.getElementById('id_date')
  M.FormSelect.init(selectEl)

</script>
{% endblock %}

main_app/templates/main_app/job_list.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/list.css' %}">
{% endblock extrahead %}
{% block content %}

<h1>All Jobs</h1>

{% for job in job_list %}
<a href="{% url 'job_detail' job.id %}">
    <div class="card card-animation">
        <div class="card-content">
            <div class="card-left">
                <span class="card-title">{{ job.company_name }}</span>
                <p>Title: {{ job.title }}</p>
            </div>
            <div class="card-right">
                {{ job.date }}
            </div>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/photo_list.html
{% extends 'base.html'%}

{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/detail.css' %}">
{% endblock extrahead %}

{% block content %}
<h1>Meme List</h1>

<form action="{% url 'add_photo' %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn" value="Upload Photo">
</form>
<div class="photo-wrapper">
{% for p in object_list %}


    <div class="card-content photo-content">



        <img class="responsive-img card-panel" src="{{p.url}}">
        



    </div>

{% empty %}
<div class="card-panel teal-text center-align">No Memes Uploaded</div>
{% endfor %}
</div>


{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %} {% block content %}


{% if object %}
<h1>Edit <span class="teal-text">{{object.user}}</span></h1>
{% else %}
<h1>Create Profile</h1>
{% endif %}

<form action="" method="post">
  
  {% csrf_token %}
  <table>
    
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}


<script>
	
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
    });

</script>
{% endblock %}

main_app/templates/main_app/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Project</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'project_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/project_detail.html
{% extends 'base.html'%}

{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/detail.css' %}">
{% endblock extrahead %}

{% block content %}

<h1>Project Details</h1>


<div class="card">
  <div class="card-content">

    <div class="card-left">
      <span class="card-title">{{ project.name }}</span>
      <br>

      <a href={{ project.link }} target="_blank" class="card-link card-animation">Link to My Project</a>
      <br>
      <p id="description">{{ project.description }} </p>
    </div>
    <div class="user-date">{{ project.user }} </div>
  </div>
  {% if project.user.id == user.id %}
  <div class="card-action" id="card-bottom">

    <a id='edit' class='underline-animation' href="{% url 'project_update' project.id %}">Edit</a>
    <a id='delete' class='underline-animation' href="{% url 'project_delete' project.id %}">Delete</a>
  </div>
  {% endif %}
</div>
<br>
<div class="col s6">
  <button class='collapsible card-animation-alt'>Add Comment</button>
  <div class='content'>
    <form method="post" action="{% url 'add_comment' project.id %}" id='new-comment-form'>
      <fieldset id="new-comment-fieldset">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" class="btn" value="Add comment" />
      </fieldset>
    </form>
  </div>
  <div class="existing-comments-wrapper">
    <table class="striped">
      <thead>
        <tr>
          <th>Comments</th>
        </tr>
      </thead>
      <tbody>
        {% for comment in project.comment_set.all %}
        <tr>
          <td>{{comment.created_on}}</td>
          <td>{{comment.comment}}</td>
          <td>{{comment.author}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>

  document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });

</script>
<script src="{% static 'scripts/detail.js' %}"></script>
{% endblock %}

main_app/templates/main_app/project_form.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/forms.css' %}">
{% endblock extrahead %}
{% block content %}


<form action="" method="post">
  <fieldset id='form-fieldset'>
    <legend>
      {% if object %}
      Edit {{object.user.username}}
      {% else %}
      Add Project
      {% endif %}
    </legend>
    {% csrf_token %}
    <table>

      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </fieldset>

</form>

<script>

  document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });

</script>

{% endblock %}

main_app/templates/main_app/project_list.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/list.css' %}">
{% endblock extrahead %}
{% block content %}

<h1>All Projects</h1>

{% for project in project_list %}
<a href="{% url 'project_detail' project.id %}">
    <div class="card  card-animation">
        <div class="card-content">
            <span class="card-title">{{ project.name }}</span>
            <div class="card-right">{{ project.user }} </div>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/profile/detail.html
{% extends 'base.html'%}

{% load static %}
{% block extrahead %}
<link rel='stylesheet' type='text/css' href="{% static 'css/detail.css' %}">
{% endblock extrahead %}

{% block content %}

<h1>Profile</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ profile.user }}</span>
      </div>
    </div>
  </div>

  <div class="col s6">
  
    {% if profile_pic %}
    <img class="responsive-img card-panel" src="{{profile_pic.url}}">
    {% else %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endif %}

    <form action="{% url 'add_profile_photo' profile.user.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
      
        {% if profile_pic %}
        <input type="submit" class="btn" value="Edit Photo">
        {% else %}
        <input type="submit" class="btn" value="Upload Photo">
        {% endif %}
    </form>

  </div>
</div>

  
  
<h1>My Projects</h1>
    <hr />
    {% for project in projects  %}
    <a href={{ project.link }} target ="_blank">{{project.link}}</a>
    <br />
      
    {% empty %}
      
    {% endfor %}
      
    {% endblock %}